channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::r-cnaqc=1.1.2
  - conda-forge::r-cli=3.6.5
  - conda-forge::r-dplyr=1.2.1
  - conda-forge::r-readr=2.1.5
  - conda-forge::r-tidyverse=2.0.0
  - conda-forge::r-vcfr=1.15.0
