FROM python:3.12-slim

ARG USER_ID=root
ENV USER_ID=$USER_ID
ENV HOME=/home/$USER_ID



# Combine apt-get commands to reduce layers and clean up after installations
RUN apt-get update && apt-get install -y --no-install-recommends \
  wget \
  build-essential \
  libgit2-dev \
  libssl-dev \
  libcurl4-openssl-dev \
  libfontconfig1-dev \
  zlib1g-dev \
  libharfbuzz-dev \
  libfribidi-dev \
  libfreetype6-dev \
  libpng-dev \
  libtiff5-dev \
  libjpeg-dev \
  libxml2-dev \
  libbz2-dev \
  liblapack-dev \
  ca-certificates \
  gcc \
  cmake \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Set the working directory and ensure it exists
WORKDIR $HOME

RUN pip install pandas SigProfilerMatrixGenerator SigProfilerExtractor

# Set appropriate permissions
RUN chmod -R ugo+rwX $HOME

# Set the default command to start a bash shell
CMD ["bash"]

