channels:
- conda-forge
- bioconda
dependencies:
- bioconda::bioconductor-complexheatmap=2.26.1
- bioconda::bioconductor-maftools=2.26.0
- conda-forge::r-dplyr=1.2.0
- conda-forge::r-ggplot2=4.0.2
- conda-forge::r-patchwork=1.3.2
- conda-forge::r-tidyr=1.3.2